# Generated by Django 5.1.6 on 2025-02-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('documentary', 'Documentary'), ('drama', 'Drama'), ('romance', 'Romance')], default='documentary', max_length=80),
        ),
        migrations.AddField(
            model_name='video',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
